# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3b869672df883b69ffb674a75db244c3e8592bcb53071e0b3a763184e7ae9fff5b5f477adb3bafc1c2e731381944a6454b35cb4f6d39f3c59250f1cda957745

test:
  secret_key_base: b53a206fa955d8931bbd100ee5420a6b6f43eb39699f4bb89b4f4fa7237c0020ff8c11fea21c16150358c606ff2f3af9e1af7a8708a18d8551de4d907d4e3e0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_s3_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_s3_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  S3_BUCKET_NAME